class OverworldMap {
  constructor(config) {
    this.overworld = null;
    this.configObjects = config.configObjects; // Configuration content
    this.gameObjects = {}; // Starts empty, live object instances in the map get added here
    this.cutsceneSpaces = config.cutsceneSpaces || {};
    this.walls = config.walls || {};

    this.lowerImage = new Image();
    this.lowerImage.src = config.lowerSrc;

    this.upperImage = new Image();
    this.upperImage.src = config.upperSrc;

    this.isCutscenePlaying = false;
    this.isPaused = false;
  }

  drawLowerImage(ctx, cameraPerson) {
    ctx.drawImage(
      this.lowerImage,
      utils.withGrid(10.5) - cameraPerson.x,
      utils.withGrid(6) - cameraPerson.y
    );
  }

  drawUpperImage(ctx, cameraPerson) {
    ctx.drawImage(
      this.upperImage,
      utils.withGrid(10.5) - cameraPerson.x,
      utils.withGrid(6) - cameraPerson.y
    );
  }

  isSpaceTaken(currentX, currentY, direction) {
    const { x, y } = utils.nextPosition(currentX, currentY, direction);
    if (this.walls[`${x},${y}`]) {
      return true;
    }
    // Check for objects that match
    return Object.values(this.gameObjects).find((obj) => {
      if (obj.x === x && obj.y === y) {
        return true;
      }
      if (
        obj.intentPosition &&
        obj.intentPosition[0] === x &&
        obj.intentPosition[1] === y
      ) {
        return true;
      }
      return false;
    });
  }

  mountObjects() {
    Object.keys(this.configObjects).forEach((key) => {
      let config = this.configObjects[key];
      config.id = key;

      let obj;
      if (config.type === "Person") {
        obj = new Person(config);
      }
      if (config.type === "PizzaStone") {
        obj = new PizzaStone(config);
      }
      this.gameObjects[key] = obj;
      this.gameObjects[key].id = key;
      obj.mount(this);
    });
  }

  async startCutscene(events) {
    this.isCutscenePlaying = true;

    for (let i = 0; i < events.length; i++) {
      const eventHandler = new OverworldEvent({
        event: events[i],
        map: this,
      });
      const result = await eventHandler.init();
      if (result === "LOST_BATTLE") {
        break;
      }
    }
    this.isCutscenePlaying = false;
  }

  checkForActionCutscene() {
    const hero = this.gameObjects["hero"];
    const nextCoords = utils.nextPosition(hero.x, hero.y, hero.direction);
    const match = Object.values(this.gameObjects).find((object) => {
      return `${object.x},${object.y}` === `${nextCoords.x},${nextCoords.y}`;
    });
    if (!this.isCutscenePlaying && match && match.talking.length) {
      const relevantScenario = match.talking.find((scenario) => {
        return (scenario.required || []).every((sf) => {
          return playerState.storyFlags[sf];
        });
      });
      relevantScenario && this.startCutscene(relevantScenario.events);
    }
  }

  checkForFootstepCutscene() {
    const hero = this.gameObjects["hero"];
    const match = this.cutsceneSpaces[`${hero.x},${hero.y}`];
    if (!this.isCutscenePlaying && match) {
      this.startCutscene(match[0].events);
    }
  }
}

window.OverworldMaps = {
  Knothole: {
    id: "Knothole",
    lowerSrc: "assets/maps/knotholeLower.png",
    upperSrc: "assets/maps/knotholeUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(31),
        y: utils.withGrid(0),
      },
      amy: {
        type: "Person",
        x: utils.withGrid(8),
        y: utils.withGrid(18),
        direction: "down",
        src: "assets/characters/people/amy.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "The chao have been so excited ever since you came back!",
                faceHero: "amy",
              },
            ],
          },
        ],
      },
      antoine: {
        type: "Person",
        x: utils.withGrid(1),
        y: utils.withGrid(6),
        direction: "right",
        src: "assets/characters/people/antoine.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Sacre bleu! What are you doing back so soon, Sonic the hedgehog?",
                faceHero: "antoine",
              },
              {
                type: "textMessage",
                text: "You shall not pass. The princess has told me to guard the way to New Mobotropolis until further notice.",
                faceHero: "antoine",
              },
            ],
          },
        ],
      },
      bunnie: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(20),
        direction: "right",
        src: "assets/characters/people/bunnie.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Welcome back sugah!",
                faceHero: "bunnie",
              },
              {
                type: "textMessage",
                text: "Amy has been worried about the chao, I know she can use some help.",
                faceHero: "bunnie",
              },
            ],
          },
        ],
      },
      dulce: {
        type: "Person",
        x: utils.withGrid(54),
        y: utils.withGrid(6),
        direction: "down",
        src: "assets/characters/people/dulce.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Sonic! Did you hear about the robots that went berserk?",
                faceHero: "dulce",
              },
              {
                type: "textMessage",
                text: "The freedom fighters got them under control of corse! Sally is working with Nicole to see what happened to them.",
                faceHero: "dulce",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 500 },
          { type: "stand", direction: "down", time: 500 },
          { type: "walk", direction: "down" },
          { type: "stand", direction: "down", time: 1000 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 500 },
          { type: "stand", direction: "down", time: 1000 },
        ],
      },
      knuckles: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(35),
        direction: "down",
        src: "assets/characters/people/knuckles.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Hey. You up for a treasure hunting adventure?",
                faceHero: "knuckles",
              },
            ],
          },
        ],
      },
      marine: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(20),
        direction: "left",
        src: "assets/characters/people/marine.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Sonic! Aren't the chao so beautiful! We don't have them in the Sol Zone.",
                faceHero: "marine",
              },
            ],
          },
        ],
      },
      mina: {
        type: "Person",
        x: utils.withGrid(55),
        y: utils.withGrid(14),
        direction: "down",
        src: "assets/characters/people/mina.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "A family of chao are following me! Maybe I can feature them at my next concert!",
                faceHero: "mina",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      rouge: {
        type: "Person",
        x: utils.withGrid(34),
        y: utils.withGrid(17),
        direction: "up",
        src: "assets/characters/people/rouge.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "I heard knuckles is looking for the master emerald again. G.U.N. has their eyes on that jewel.",
              },
            ],
          },
        ],
      },
      shade: {
        type: "Person",
        x: utils.withGrid(12),
        y: utils.withGrid(37),
        direction: "up",
        src: "assets/characters/people/shade.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "This world is a lot to wrap my head around, but I'm glad I have you all to help.",
              },
            ],
          },
        ],
      },
      shadow: {
        type: "Person",
        x: utils.withGrid(34),
        y: utils.withGrid(16),
        direction: "down",
        src: "assets/characters/people/shadow.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Not now Sonic. We're busy.",
                faceHero: "shadow",
              },
            ],
          },
        ],
      },
      tails: {
        type: "Person",
        x: utils.withGrid(37),
        y: utils.withGrid(28),
        direction: "up",
        src: "assets/characters/people/tails.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Hey Sonic! I'm taking apart this e-1000 unit to understand why they went haywire the other day.",
                faceHero: "tails",
              },
              {
                type: "textMessage",
                text: "I don't remember where all of the parts went though. Can you help me?",
                faceHero: "tails",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "up", time: 1000 },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "down", time: 1000 },
        ],
      },
      vector: {
        type: "Person",
        x: utils.withGrid(57),
        y: utils.withGrid(35),
        direction: "down",
        src: "assets/characters/people/vector.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "The Chaotix are assigned another mystery! Espio and Charmy aren't here but Mighty, Saffron and I got it handled!",
                faceHero: "vector",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "stand", direction: "down", time: 2500 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 2500 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
        ],
      },
      gamma1: {
        type: "Person",
        x: utils.withGrid(60),
        y: utils.withGrid(6),
        direction: "left",
        src: "assets/characters/people/gamma.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "*whirllllll*",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "stand", direction: "right", time: 500 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 1000 },
        ],
      },
      gamma2: {
        type: "Person",
        x: utils.withGrid(60),
        y: utils.withGrid(7),
        direction: "left",
        src: "assets/characters/people/gamma.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "*Zappppppp*",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "stand", direction: "right", time: 300 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 453 },
        ],
      },
      gamma3: {
        type: "Person",
        x: utils.withGrid(60),
        y: utils.withGrid(8),
        direction: "left",
        src: "assets/characters/people/gamma.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "*Bzzzzzzzztt*",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "stand", direction: "right", time: 976 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 860 },
        ],
      },
      gamma4: {
        type: "Person",
        x: utils.withGrid(36),
        y: utils.withGrid(27),
        direction: "down",
        src: "assets/characters/people/gamma.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Err... or.",
              },
            ],
          },
        ],
      },
      fiona: {
        type: "Person",
        x: utils.withGrid(17),
        y: utils.withGrid(12),
        direction: "down",
        src: "assets/characters/people/fiona.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Why do they get to be so happy... Where is Scourge...",
              },
            ],
          },
        ],
      },
      saffron: {
        type: "Person",
        x: utils.withGrid(56),
        y: utils.withGrid(36),
        direction: "right",
        src: "assets/characters/people/saffron.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "With Vector in charge, we can do anything!",
                faceHero: "saffron",
              },
            ],
          },
        ],
      },
      mighty: {
        type: "Person",
        x: utils.withGrid(58),
        y: utils.withGrid(36),
        direction: "left",
        src: "assets/characters/people/mighty.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "We got this.",
                faceHero: "mighty",
              },
            ],
          },
        ],
      },
      sally: {
        type: "Person",
        x: utils.withGrid(58),
        y: utils.withGrid(7),
        direction: "right",
        src: "assets/characters/people/sally.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Sonic, glad to hear your mission went well, but I don't have time for a debrief.",
                faceHero: "sally",
              },
              {
                type: "textMessage",
                text: "The e-1000s are acting up and I'm worried it has to do with Robotnik.",
              },
              {
                type: "textMessage",
                text: "Can you run and get me something? Let's do it to it!",
                faceHero: "sally",
              },
            ],
          },
        ],
      },
      laraSu: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(38),
        direction: "right",
        src: "assets/characters/people/lara-su.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Knuckles is so stubborn.",
                faceHero: "laraSu",
              },
            ],
          },
        ],
      },
      cream: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(22),
        direction: "right",
        src: "assets/characters/people/cream.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Cheese, wait for me!",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
        ],
      },
      robO: {
        type: "Person",
        x: utils.withGrid(34),
        y: utils.withGrid(37),
        direction: "down",
        src: "assets/characters/people/rob-o.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Hey there Sonic! Have you had a chance to speak with my cousin? I hear she is in need of help in the Chao Garden.",
                faceHero: "robO",
              },
              {
                type: "textMessage",
                text: "I'm looking for flickies hiding in the tall grass.",
                faceHero: "robO",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "stand", direction: "left", time: 150 },
          { type: "stand", direction: "right", time: 100 },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "stand", direction: "down", time: 500 },
          { type: "walk", direction: "left" },
          { type: "stand", direction: "left", time: 100 },
          { type: "stand", direction: "right", time: 150 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "left", time: 100 },
          { type: "stand", direction: "right", time: 100 },
        ],
      },
      nicole: {
        type: "Person",
        x: utils.withGrid(59),
        y: utils.withGrid(5),
        direction: "down",
        src: "assets/characters/people/nicole.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "I'm helping Sally diagnose the e-1000 robots with my nanites. I can't interface with them right now for some reason.",
                faceHero: "nicole",
              },
              {
                type: "textMessage",
                text: "The reason you can see me right now is beacuse I am projecting myself using a special technology.",
                faceHero: "nicole",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "left" },
          { type: "walk", direction: "down" },
          { type: "stand", direction: "down", time: 500 },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "right", time: 500 },
          { type: "walk", direction: "up" },
        ],
      },
      uncleChuck: {
        type: "Person",
        x: utils.withGrid(38),
        y: utils.withGrid(32),
        direction: "down",
        src: "assets/characters/people/uncle-chuck.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Sonic my boy! How was your last adventure? I've been in the shop the past few hours helping Tails diagnose the bots.",
                faceHero: "uncleChuck",
              },
              {
                type: "textMessage",
                text: "Have you talked to him yet? I'm sure you would be a great help to him!",
                faceHero: "uncleChuck",
              },
            ],
          },
        ],
      },
      chaos: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(17),
        direction: "down",
        src: "assets/characters/people/chaos.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "...",
              },
            ],
          },
        ],
      },
      tPup: {
        type: "Person",
        x: utils.withGrid(38),
        y: utils.withGrid(28),
        direction: "left",
        src: "assets/characters/people/t-pup-sky.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      omachao: {
        type: "Person",
        x: utils.withGrid(29),
        y: utils.withGrid(9),
        direction: "right",
        src: "assets/characters/people/omachao.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "You've been gone for a few weeks on a mission Sonic. Go speak to your friends and see if they need any help.",
                faceHero: "omachao",
              },
              {
                type: "textMessage",
                text: "Amy is in the chao garden. Knuckles is across the southern bridge. Tails is near your house. Sally is to the east.",
                faceHero: "omachao",
              },
            ],
          },
        ],
      },
      cheese: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(22),
        direction: "left",
        src: "assets/characters/people/cheese.png",
        talking: [
          {
            events: [
              {
                type: "textMessage",
                text: "Chao chao chao.",
                faceHero: "cheese",
              },
            ],
          },
        ],
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
        ],
      },

      // Chao
      chao1: {
        type: "Person",
        x: utils.withGrid(20),
        y: utils.withGrid(4),
        direction: "right",
        src: "assets/characters/people/chao.png",
      },
      chao2: {
        type: "Person",
        x: utils.withGrid(21),
        y: utils.withGrid(4),
        direction: "left",
        src: "assets/characters/people/hero-chao.png",
      },
      chao3: {
        type: "Person",
        x: utils.withGrid(50),
        y: utils.withGrid(5),
        direction: "right",
        src: "assets/characters/people/hero-chao.png",
      },
      chao4: {
        type: "Person",
        x: utils.withGrid(51),
        y: utils.withGrid(5),
        direction: "left",
        src: "assets/characters/people/chao.png",
      },
      chao5: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(7),
        direction: "left",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
        ],
      },
      chao6: {
        type: "Person",
        x: utils.withGrid(43),
        y: utils.withGrid(8),
        direction: "right",
        src: "assets/characters/people/chao.png",
      },
      chao7: {
        type: "Person",
        x: utils.withGrid(44),
        y: utils.withGrid(8),
        direction: "left",
        src: "assets/characters/people/chao.png",
      },
      chao8: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(9),
        direction: "up",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
        ],
      },
      chao9: {
        type: "Person",
        x: utils.withGrid(6),
        y: utils.withGrid(9),
        direction: "left",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao10: {
        type: "Person",
        x: utils.withGrid(56),
        y: utils.withGrid(10),
        direction: "down",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao11: {
        type: "Person",
        x: utils.withGrid(55),
        y: utils.withGrid(11),
        direction: "down",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao12: {
        type: "Person",
        x: utils.withGrid(54),
        y: utils.withGrid(12),
        direction: "down",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao13: {
        type: "Person",
        x: utils.withGrid(55),
        y: utils.withGrid(12),
        direction: "down",
        src: "assets/characters/people/hero-chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao14: {
        type: "Person",
        x: utils.withGrid(20),
        y: utils.withGrid(13),
        direction: "down",
        src: "assets/characters/people/dark-chao.png",
      },
      chao15: {
        type: "Person",
        x: utils.withGrid(55),
        y: utils.withGrid(13),
        direction: "left",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },

          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "left" },

          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },

          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },

          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
        ],
      },
      chao16: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(14),
        direction: "right",
        src: "assets/characters/people/hero-chao.png",
      },
      chao17: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(14),
        direction: "left",
        src: "assets/characters/people/chao.png",
      },
      chao18: {
        type: "Person",
        x: utils.withGrid(8),
        y: utils.withGrid(15),
        direction: "down",
        src: "assets/characters/people/dark-chao.png",
      },
      chao19: {
        type: "Person",
        x: utils.withGrid(36),
        y: utils.withGrid(15),
        direction: "down",
        src: "assets/characters/people/dark-chao.png",
      },
      chao20: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(16),
        direction: "right",
        src: "assets/characters/people/hero-chao.png",
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
        ],
      },
      chao21: {
        type: "Person",
        x: utils.withGrid(6),
        y: utils.withGrid(16),
        direction: "down",
        src: "assets/characters/people/hero-chao.png",
        behaviorLoop: [
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
        ],
      },
      chao22: {
        type: "Person",
        x: utils.withGrid(9),
        y: utils.withGrid(16),
        direction: "left",
        src: "assets/characters/people/chao.png",
      },
      chao23: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(18),
        direction: "left",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
        ],
      },
      chao24: {
        type: "Person",
        x: utils.withGrid(58),
        y: utils.withGrid(19),
        direction: "down",
        src: "assets/characters/people/hero-chao.png",
      },
      chao25: {
        type: "Person",
        x: utils.withGrid(58),
        y: utils.withGrid(20),
        direction: "up",
        src: "assets/characters/people/dark-chao.png",
      },
      chao26: {
        type: "Person",
        x: utils.withGrid(10),
        y: utils.withGrid(22),
        direction: "up",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "left", time: 250 },
          { type: "stand", direction: "right", time: 750 },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "stand", direction: "right", time: 500 },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "stand", direction: "left", time: 300 },
          { type: "stand", direction: "down", time: 400 },
        ],
      },
      chao27: {
        type: "Person",
        x: utils.withGrid(26),
        y: utils.withGrid(25),
        direction: "up",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
        ],
      },
      chao28: {
        type: "Person",
        x: utils.withGrid(38),
        y: utils.withGrid(25),
        direction: "right",
        src: "assets/characters/people/hero-chao.png",
      },
      chao29: {
        type: "Person",
        x: utils.withGrid(39),
        y: utils.withGrid(25),
        direction: "left",
        src: "assets/characters/people/hero-chao.png",
      },
      chao30: {
        type: "Person",
        x: utils.withGrid(26),
        y: utils.withGrid(27),
        direction: "up",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
        ],
      },
      chao31: {
        type: "Person",
        x: utils.withGrid(26),
        y: utils.withGrid(29),
        direction: "up",
        src: "assets/characters/people/dark-chao.png",
        behaviorLoop: [
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "up" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "down" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "up" },
        ],
      },
      chao32: {
        type: "Person",
        x: utils.withGrid(4),
        y: utils.withGrid(35),
        direction: "right",
        src: "assets/characters/people/chao.png",
      },
      chao33: {
        type: "Person",
        x: utils.withGrid(6),
        y: utils.withGrid(35),
        direction: "left",
        src: "assets/characters/people/chao.png",
      },
      chao34: {
        type: "Person",
        x: utils.withGrid(2),
        y: utils.withGrid(36),
        direction: "down",
        src: "assets/characters/people/chao.png",
      },
      chao35: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(36),
        direction: "right",
        src: "assets/characters/people/chao.png",
      },
      chao36: {
        type: "Person",
        x: utils.withGrid(3),
        y: utils.withGrid(39),
        direction: "up",
        src: "assets/characters/people/chao.png",
      },
      chao37: {
        type: "Person",
        x: utils.withGrid(5),
        y: utils.withGrid(39),
        direction: "right",
        src: "assets/characters/people/chao.png",
        behaviorLoop: [
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "walk", direction: "right" },
          { type: "stand", direction: "up", time: 500 },
          { type: "stand", direction: "right", time: 200 },
          { type: "stand", direction: "left", time: 150 },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
          { type: "walk", direction: "left" },
        ],
      },
      // grass: {
      //   type: "grass",
      //   x: utils.withGrid(1),
      //   y: utils.withGrid(4),
      // },
    },
    cutsceneSpaces: {
      [utils.asGridCoord(40, 24)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Home",
              x: utils.withGrid(0),
              y: utils.withGrid(0),
              direction: "up",
            },
          ],
        },
      ],
      [utils.asGridCoord(41, 24)]: [
        {
          events: [
            {
              type: "changeMap",
              map: "Home",
              x: utils.withGrid(0),
              y: utils.withGrid(0),
              direction: "up",
            },
          ],
        },
      ],

      [utils.asGridCoord(29, 0)]: [
        {
          events: [
            {
              type: "textMessage",
              text: "I can't leave yet, I just got here!",
            },
            { type: "walk", who: "hero", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(30, 0)]: [
        {
          events: [
            {
              type: "textMessage",
              text: "I can't leave yet, I just got here!",
            },
            { type: "walk", who: "hero", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(31, 0)]: [
        {
          events: [
            {
              type: "textMessage",
              text: "I can't leave yet, I just got here!",
            },
            { type: "walk", who: "hero", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(32, 0)]: [
        {
          events: [
            {
              type: "textMessage",
              text: "I can't leave yet, I just got here!",
            },
            { type: "walk", who: "hero", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(33, 0)]: [
        {
          events: [
            {
              type: "textMessage",
              text: "I can't leave yet, I just got here!",
            },
            { type: "walk", who: "hero", direction: "down" },
          ],
        },
      ],

      [utils.asGridCoord(28, 6)]: [
        {
          events: [
            { type: "stand", who: "hero", direction: "up" },

            {
              type: "textMessage",
              text: "The sign says... Welcome to Knothole, home of the Freedom Fighters!",
            },
          ],
        },
      ],

      [utils.asGridCoord(7, 37)]: [
        {
          disqualify: ["ECHIDNA_SCENE"],
          events: [
            { type: "addStoryFlag", flag: "ECHIDNA_SCENE" },

            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },
            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },

            {
              type: "textMessage",
              text: "Knuckles, I can't stand around when the master emerald is gone!",
            },
            {
              type: "textMessage",
              text: "Let me help! You're not alone anymore.",
            },

            { type: "walk", who: "chao32", direction: "left" },
            { type: "stand", who: "chao32", direction: "down" },
            { type: "walk", who: "chao33", direction: "right" },
            { type: "stand", who: "chao33", direction: "down" },
            { type: "walk", who: "knuckles", direction: "left" },
            { type: "walk", who: "knuckles", direction: "down" },
            { type: "stand", who: "knuckles", direction: "right" },
            { type: "stand", who: "laraSu", direction: "left" },

            {
              type: "textMessage",
              text: "I won't go alone. Now that Sonic is here, we can go together.",
            },

            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "stand", who: "laraSu", direction: "right" },

            { type: "walk", who: "knuckles", direction: "right" },
            { type: "walk", who: "knuckles", direction: "up" },
            { type: "stand", who: "laraSu", direction: "down" },

            { type: "stand", who: "knuckles", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(7, 38)]: [
        {
          disqualify: ["ECHIDNA_SCENE"],
          events: [
            { type: "addStoryFlag", flag: "ECHIDNA_SCENE" },

            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },
            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },

            {
              type: "textMessage",
              text: "Knuckles, I can't stand around when the master emerald is gone!",
            },
            {
              type: "textMessage",
              text: "Let me help! You're not alone anymore.",
            },

            { type: "walk", who: "chao32", direction: "left" },
            { type: "stand", who: "chao32", direction: "down" },
            { type: "walk", who: "chao33", direction: "right" },
            { type: "stand", who: "chao33", direction: "down" },
            { type: "walk", who: "knuckles", direction: "left" },
            { type: "walk", who: "knuckles", direction: "down" },
            { type: "stand", who: "knuckles", direction: "right" },

            {
              type: "textMessage",
              text: "I won't go alone. Now that Sonic is here, we can go together.",
            },

            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "stand", who: "laraSu", direction: "right" },

            { type: "walk", who: "knuckles", direction: "right" },
            { type: "walk", who: "knuckles", direction: "up" },
            { type: "stand", who: "laraSu", direction: "down" },
          ],
        },
      ],
      [utils.asGridCoord(7, 39)]: [
        {
          disqualify: ["ECHIDNA_SCENE"],
          events: [
            { type: "addStoryFlag", flag: "ECHIDNA_SCENE" },

            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },
            { type: "walk", who: "laraSu", direction: "right" },
            { type: "walk", who: "laraSu", direction: "up" },

            {
              type: "textMessage",
              text: "Knuckles, I can't stand around when the master emerald is gone!",
            },
            {
              type: "textMessage",
              text: "Let me help! You're not alone anymore.",
            },

            { type: "walk", who: "chao32", direction: "left" },
            { type: "stand", who: "chao32", direction: "down" },
            { type: "walk", who: "chao33", direction: "right" },
            { type: "stand", who: "chao33", direction: "down" },
            { type: "walk", who: "knuckles", direction: "left" },
            { type: "walk", who: "knuckles", direction: "down" },
            { type: "stand", who: "knuckles", direction: "right" },

            {
              type: "textMessage",
              text: "I won't go alone. Now that Sonic is here, we can go together.",
            },

            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "down" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "walk", who: "laraSu", direction: "left" },
            { type: "stand", who: "laraSu", direction: "right" },

            { type: "walk", who: "knuckles", direction: "right" },
            { type: "walk", who: "knuckles", direction: "up" },
            { type: "stand", who: "laraSu", direction: "down" },
          ],
        },
      ],
      // [utils.asGridCoord(0, 6)]: [
      //   {
      //     events: [
      //       {
      //         type: "changeMap",
      //         map: "xxx",
      //         x: utils.withGrid(0),
      //         y: utils.withGrid(0),
      //         direction: "left",
      //       },
      //     ],
      //   },
      // ],
      // [utils.asGridCoord(62, 6)]: [
      //   {
      //     events: [
      //       {
      //         type: "changeMap",
      //         map: "Home",
      //         x: utils.withGrid(0),
      //         y: utils.withGrid(0),
      //         direction: "right",
      //       },
      //     ],
      //   },
      // ],
      // [utils.asGridCoord(62, 7)]: [
      //   {
      //     events: [
      //       {
      //         type: "changeMap",
      //         map: "Home",
      //         x: utils.withGrid(0),
      //         y: utils.withGrid(0),
      //         direction: "right",
      //       },
      //     ],
      //   },
      // ],
      // [utils.asGridCoord(62, 8)]: [
      //   {
      //     events: [
      //       {
      //         type: "changeMap",
      //         map: "Home",
      //         x: utils.withGrid(0),
      //         y: utils.withGrid(0),
      //         direction: "right",
      //       },
      //     ],
      //   },
      // ],
    },
    walls: {
      // Top Left
      [utils.asGridCoord(0, 5)]: true,
      [utils.asGridCoord(1, 5)]: true,
      [utils.asGridCoord(1, 4)]: true,
      [utils.asGridCoord(1, 3)]: true,
      [utils.asGridCoord(2, 2)]: true,
      [utils.asGridCoord(3, 3)]: true,
      [utils.asGridCoord(4, 3)]: true,
      [utils.asGridCoord(5, 2)]: true,
      [utils.asGridCoord(6, 3)]: true,
      [utils.asGridCoord(7, 4)]: true,
      [utils.asGridCoord(8, 4)]: true,
      [utils.asGridCoord(9, 4)]: true,
      [utils.asGridCoord(10, 4)]: true,
      [utils.asGridCoord(11, 4)]: true,
      [utils.asGridCoord(12, 4)]: true,
      [utils.asGridCoord(13, 4)]: true,
      [utils.asGridCoord(14, 4)]: true,
      [utils.asGridCoord(15, 4)]: true,
      [utils.asGridCoord(16, 4)]: true,
      [utils.asGridCoord(17, 4)]: true,
      [utils.asGridCoord(18, 3)]: true,
      [utils.asGridCoord(19, 2)]: true,
      [utils.asGridCoord(20, 2)]: true,
      [utils.asGridCoord(21, 3)]: true,
      [utils.asGridCoord(22, 3)]: true,
      [utils.asGridCoord(23, 2)]: true,
      [utils.asGridCoord(24, 2)]: true,
      [utils.asGridCoord(25, 3)]: true,
      [utils.asGridCoord(25, 4)]: true,
      [utils.asGridCoord(26, 4)]: true,
      [utils.asGridCoord(27, 4)]: true,
      [utils.asGridCoord(28, 5)]: true,
      [utils.asGridCoord(28, 4)]: true,
      [utils.asGridCoord(28, 3)]: true,
      [utils.asGridCoord(28, 2)]: true,
      [utils.asGridCoord(28, 1)]: true,
      [utils.asGridCoord(28, 0)]: true,

      // Top Right
      [utils.asGridCoord(34, 0)]: true,
      [utils.asGridCoord(34, 1)]: true,
      [utils.asGridCoord(34, 2)]: true,
      [utils.asGridCoord(34, 3)]: true,
      [utils.asGridCoord(34, 4)]: true,
      [utils.asGridCoord(35, 4)]: true,
      [utils.asGridCoord(36, 4)]: true,
      [utils.asGridCoord(37, 4)]: true,
      [utils.asGridCoord(37, 3)]: true,
      [utils.asGridCoord(38, 2)]: true,
      [utils.asGridCoord(39, 2)]: true,
      [utils.asGridCoord(40, 3)]: true,
      [utils.asGridCoord(41, 3)]: true,
      [utils.asGridCoord(42, 2)]: true,
      [utils.asGridCoord(43, 3)]: true,
      [utils.asGridCoord(44, 3)]: true,
      [utils.asGridCoord(45, 2)]: true,
      [utils.asGridCoord(46, 2)]: true,
      [utils.asGridCoord(47, 2)]: true,
      [utils.asGridCoord(48, 3)]: true,
      [utils.asGridCoord(49, 3)]: true,
      [utils.asGridCoord(50, 3)]: true,
      [utils.asGridCoord(51, 2)]: true,
      [utils.asGridCoord(52, 2)]: true,
      [utils.asGridCoord(53, 2)]: true,
      [utils.asGridCoord(54, 3)]: true,
      [utils.asGridCoord(55, 3)]: true,
      [utils.asGridCoord(56, 2)]: true,
      [utils.asGridCoord(57, 3)]: true,
      [utils.asGridCoord(58, 3)]: true,
      [utils.asGridCoord(59, 2)]: true,
      [utils.asGridCoord(60, 2)]: true,
      [utils.asGridCoord(61, 3)]: true,
      [utils.asGridCoord(62, 4)]: true,
      [utils.asGridCoord(61, 5)]: true,
      [utils.asGridCoord(62, 5)]: true,

      // Left trees
      [utils.asGridCoord(0, 7)]: true,
      [utils.asGridCoord(1, 7)]: true,
      [utils.asGridCoord(2, 7)]: true,
      [utils.asGridCoord(2, 8)]: true,
      [utils.asGridCoord(2, 9)]: true,
      [utils.asGridCoord(2, 10)]: true,
      [utils.asGridCoord(2, 11)]: true,
      [utils.asGridCoord(3, 11)]: true,
      [utils.asGridCoord(4, 11)]: true,
      [utils.asGridCoord(4, 12)]: true,
      [utils.asGridCoord(4, 13)]: true,
      [utils.asGridCoord(3, 13)]: true,
      [utils.asGridCoord(2, 13)]: true,
      [utils.asGridCoord(2, 14)]: true,
      [utils.asGridCoord(2, 15)]: true,
      [utils.asGridCoord(2, 16)]: true,
      [utils.asGridCoord(2, 17)]: true,
      [utils.asGridCoord(2, 18)]: true,
      [utils.asGridCoord(2, 19)]: true,
      [utils.asGridCoord(2, 20)]: true,
      [utils.asGridCoord(2, 21)]: true,
      [utils.asGridCoord(2, 22)]: true,
      [utils.asGridCoord(2, 23)]: true,
      [utils.asGridCoord(3, 24)]: true,
      [utils.asGridCoord(4, 24)]: true,
      [utils.asGridCoord(5, 24)]: true,
      [utils.asGridCoord(6, 24)]: true,
      [utils.asGridCoord(7, 24)]: true,
      [utils.asGridCoord(8, 25)]: true,
      [utils.asGridCoord(9, 24)]: true,
      [utils.asGridCoord(10, 23)]: true,
      [utils.asGridCoord(11, 22)]: true,
      [utils.asGridCoord(11, 21)]: true,
      [utils.asGridCoord(11, 20)]: true,
      [utils.asGridCoord(11, 19)]: true,
      [utils.asGridCoord(11, 18)]: true,
      [utils.asGridCoord(11, 17)]: true,
      [utils.asGridCoord(11, 16)]: true,
      [utils.asGridCoord(10, 15)]: true,
      [utils.asGridCoord(10, 14)]: true,
      [utils.asGridCoord(9, 13)]: true,
      [utils.asGridCoord(8, 13)]: true,
      [utils.asGridCoord(7, 13)]: true,
      [utils.asGridCoord(6, 13)]: true,
      [utils.asGridCoord(6, 12)]: true,
      [utils.asGridCoord(6, 11)]: true,
      [utils.asGridCoord(7, 11)]: true,
      [utils.asGridCoord(8, 11)]: true,
      [utils.asGridCoord(9, 10)]: true,
      [utils.asGridCoord(9, 9)]: true,
      [utils.asGridCoord(9, 8)]: true,
      [utils.asGridCoord(10, 8)]: true,
      [utils.asGridCoord(11, 8)]: true,
      [utils.asGridCoord(12, 8)]: true,
      [utils.asGridCoord(13, 8)]: true,
      [utils.asGridCoord(14, 8)]: true,
      [utils.asGridCoord(15, 8)]: true,
      [utils.asGridCoord(16, 8)]: true,
      [utils.asGridCoord(17, 8)]: true,
      [utils.asGridCoord(18, 8)]: true,
      [utils.asGridCoord(19, 8)]: true,
      [utils.asGridCoord(19, 9)]: true,
      [utils.asGridCoord(19, 10)]: true,
      [utils.asGridCoord(18, 10)]: true,
      [utils.asGridCoord(17, 10)]: true,
      [utils.asGridCoord(16, 10)]: true,
      [utils.asGridCoord(15, 10)]: true,
      [utils.asGridCoord(14, 11)]: true,
      [utils.asGridCoord(14, 12)]: true,
      [utils.asGridCoord(14, 13)]: true,
      [utils.asGridCoord(15, 14)]: true,
      [utils.asGridCoord(16, 14)]: true,
      [utils.asGridCoord(17, 14)]: true,
      [utils.asGridCoord(18, 14)]: true,
      [utils.asGridCoord(19, 14)]: true,
      [utils.asGridCoord(20, 14)]: true,
      [utils.asGridCoord(21, 14)]: true,
      [utils.asGridCoord(22, 13)]: true,
      [utils.asGridCoord(22, 12)]: true,
      [utils.asGridCoord(22, 11)]: true,
      [utils.asGridCoord(21, 10)]: true,
      [utils.asGridCoord(21, 9)]: true,
      [utils.asGridCoord(21, 8)]: true,
      [utils.asGridCoord(22, 8)]: true,
      [utils.asGridCoord(23, 7)]: true,
      [utils.asGridCoord(24, 7)]: true,
      [utils.asGridCoord(25, 7)]: true,
      [utils.asGridCoord(26, 7)]: true,
      [utils.asGridCoord(26, 8)]: true,
      [utils.asGridCoord(26, 9)]: true,
      [utils.asGridCoord(27, 10)]: true,
      [utils.asGridCoord(28, 10)]: true,
      [utils.asGridCoord(28, 11)]: true,
      [utils.asGridCoord(28, 12)]: true,
      [utils.asGridCoord(28, 13)]: true,
      [utils.asGridCoord(28, 14)]: true,
      [utils.asGridCoord(28, 15)]: true,
      [utils.asGridCoord(28, 16)]: true,
      [utils.asGridCoord(27, 17)]: true,
      [utils.asGridCoord(26, 18)]: true,
      [utils.asGridCoord(26, 19)]: true,
      [utils.asGridCoord(25, 20)]: true,
      [utils.asGridCoord(25, 21)]: true,
      [utils.asGridCoord(25, 22)]: true,
      [utils.asGridCoord(24, 23)]: true,
      [utils.asGridCoord(23, 24)]: true,
      [utils.asGridCoord(22, 25)]: true,
      [utils.asGridCoord(21, 26)]: true,
      [utils.asGridCoord(22, 27)]: true,
      [utils.asGridCoord(22, 28)]: true,
      [utils.asGridCoord(23, 29)]: true,
      [utils.asGridCoord(24, 30)]: true,

      [utils.asGridCoord(24, 25)]: true,
      [utils.asGridCoord(25, 26)]: true,
      [utils.asGridCoord(24, 27)]: true,

      // Start of tree below extra grass
      // [utils.asGridCoord(25, 29)]: true,
      // [utils.asGridCoord(26, 30)]: true,
      // [utils.asGridCoord(27, 31)]: true,
      // [utils.asGridCoord(27, 31)]: true,
      // [utils.asGridCoord(27, 31)]: true,
      // [utils.asGridCoord(28, 32)]: true,
      // [utils.asGridCoord(28, 33)]: true,
      // [utils.asGridCoord(28, 34)]: true,
      // [utils.asGridCoord(28, 35)]: true,
      // [utils.asGridCoord(27, 36)]: true,
      // [utils.asGridCoord(26, 37)]: true,
      // [utils.asGridCoord(25, )]: true,
      // [utils.asGridCoord(24, )]: true,
      // [utils.asGridCoord(23, )]: true,
      // [utils.asGridCoord(22, )]: true,
      // [utils.asGridCoord(21, )]: true,
      // [utils.asGridCoord(20, )]: true,
      // [utils.asGridCoord(19, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(17, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(15, )]: true,
      // [utils.asGridCoord(14, )]: true,
      // [utils.asGridCoord(15, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(16, )]: true,

      // [utils.asGridCoord(17, )]: true,

      // // Top of Bridge
      // [utils.asGridCoord(15, )]: true,
      // [utils.asGridCoord(14, )]: true,
      // [utils.asGridCoord(13, )]: true,
      // [utils.asGridCoord(12, )]: true,
      // [utils.asGridCoord(11, )]: true,
      // [utils.asGridCoord(10, )]: true,
      // [utils.asGridCoord(9, )]: true,
      // [utils.asGridCoord(8, )]: true,

      // [utils.asGridCoord(7, )]: true,

      // [utils.asGridCoord(8, )]: true,
      // [utils.asGridCoord(7, )]: true,
      // [utils.asGridCoord(6, )]: true,
      // [utils.asGridCoord(5, )]: true,
      // [utils.asGridCoord(4, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(4, )]: true,
      // [utils.asGridCoord(5, )]: true,
      // [utils.asGridCoord(6, )]: true,
      // [utils.asGridCoord(7, )]: true,
      // [utils.asGridCoord(8, )]: true,
      // [utils.asGridCoord(8, )]: true,
      // [utils.asGridCoord(7, )]: true,
      // [utils.asGridCoord(6, )]: true,
      // [utils.asGridCoord(5, )]: true,
      // [utils.asGridCoord(4, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(2, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(1, )]: true,
      // [utils.asGridCoord(2, )]: true,
      // [utils.asGridCoord(3, )]: true,
      // [utils.asGridCoord(4, )]: true,
      // [utils.asGridCoord(5, )]: true,
      // [utils.asGridCoord(6, )]: true,
      // [utils.asGridCoord(7, )]: true,
      // [utils.asGridCoord(8, )]: true,
      // [utils.asGridCoord(9, )]: true,
      // [utils.asGridCoord(10, )]: true,
      // [utils.asGridCoord(11, )]: true,
      // [utils.asGridCoord(12, )]: true,
      // [utils.asGridCoord(13, )]: true,
      // [utils.asGridCoord(14, )]: true,
      // [utils.asGridCoord(15, )]: true,
      // [utils.asGridCoord(16, )]: true,
      // [utils.asGridCoord(17, )]: true,
      // [utils.asGridCoord(18, )]: true,
      // [utils.asGridCoord(19, )]: true,
      // [utils.asGridCoord(20, )]: true,
      // [utils.asGridCoord(21, )]: true,
      // [utils.asGridCoord(22, )]: true,
      // [utils.asGridCoord(23, )]: true,
      // [utils.asGridCoord(24, )]: true,
      // [utils.asGridCoord(25, )]: true,
      // [utils.asGridCoord(26, )]: true,
      // [utils.asGridCoord(27, )]: true,
      // [utils.asGridCoord(28, )]: true,
      // [utils.asGridCoord(29, )]: true,
      // [utils.asGridCoord(30, )]: true,
      // [utils.asGridCoord(31, )]: true,
      // [utils.asGridCoord(32, )]: true,
      // [utils.asGridCoord(33, )]: true,
      // [utils.asGridCoord(34, )]: true,
      // [utils.asGridCoord(35, )]: true,
      // [utils.asGridCoord(36, )]: true,
      // [utils.asGridCoord(37, )]: true,
      // [utils.asGridCoord(38, )]: true,
      // [utils.asGridCoord(39, )]: true,
      // [utils.asGridCoord(40, )]: true,
      // [utils.asGridCoord(41, )]: true,
      // [utils.asGridCoord(41, )]: true,
      // [utils.asGridCoord(42, )]: true,
      // [utils.asGridCoord(43, )]: true,
      // [utils.asGridCoord(44, )]: true,
      // [utils.asGridCoord(45, )]: true,
      // [utils.asGridCoord(46, )]: true,
      // [utils.asGridCoord(47, )]: true,
      // [utils.asGridCoord(48, )]: true,
      // [utils.asGridCoord(49, )]: true,
      // [utils.asGridCoord(50, )]: true,
      // [utils.asGridCoord(51, )]: true,
      // [utils.asGridCoord(52, )]: true,
      // [utils.asGridCoord(52, )]: true,
      // [utils.asGridCoord(52, )]: true,
      // [utils.asGridCoord(53, )]: true,
      // [utils.asGridCoord(54, )]: true,
      // [utils.asGridCoord(55, )]: true,
      // [utils.asGridCoord(56, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(58, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(60, )]: true,
      // [utils.asGridCoord(60, )]: true,
      // [utils.asGridCoord(60, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(58, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(56, )]: true,
      // [utils.asGridCoord(56, )]: true,
      // [utils.asGridCoord(56, )]: true,
      // [utils.asGridCoord(56, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(58, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(59, )]: true,

      // // After tree
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(62, )]: true,
      // [utils.asGridCoord(62, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(60, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(58, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(57, )]: true,
      // [utils.asGridCoord(58, )]: true,
      // [utils.asGridCoord(59, )]: true,
      // [utils.asGridCoord(60, )]: true,
      // [utils.asGridCoord(61, )]: true,
      // [utils.asGridCoord(62, )]: true,
    },
  },
  Home: {
    id: "Home",
    lowerSrc: "assets/maps/homeLower.png",
    upperSrc: "assets/maps/homeUpper.png",
    configObjects: {
      hero: {
        type: "Person",
        isPlayerControlled: true,
        x: utils.withGrid(3),
        y: utils.withGrid(9),
      },
    },
    cutsceneSpaces: {
      [utils.asGridCoord(10, 6)]: [
        {
          disqualify: ["BEAT_GAME"],
          events: [
            { type: "addStoryFlag", flag: "BEAT_GAME" },
            {
              type: "textMessage",
              text: "* You are chopping ingredients on your first day as a Pizza Chef at a famed establishment in town. *",
            },
          ],
        },
      ],
    },
    walls: {
      [utils.asGridCoord(0, 5)]: true,
    },
  },
};
